spring:
  application:
    name: post-code
  profiles:
    active: default
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:postcode
    password: "password"
    username: "sa"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  springdoc:
    packagesToScan=com.wcc
wcc:
  rest:
    username: "root"
    password: "root"
